### ISSUE TITLE
Could not get dex volume

### ISSUE THREAD

**Issue by Qmeasure** [coindataschool/defillama2#2]
> from defillama2 import DefiLlama
> import pandas as pd
> import numpy as np
> obj = DefiLlama()
> dd = obj.get_dexes_volumes()
> dd.keys()

Running the above code and it returns
**KeyError: "['protocolsStats'] not found in axis"**

**Comment by coindataschool** [comment]
Oh, DefiLlama dropped 'protocolsStats' from their API. Fixed now. Enjoy.
